version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0
    environment:
      TZ: "/usr/share/zoneinfo/America/Argentina/Buenos_Aires"
    paralelism: 2
    steps:
      - add_ssh_keys:
          fingerprints:
          - "2b:d1:13:72:6c:a2:d1:4c:30:a5:a7:e5:b4:52:ee:75"
      - run: git config --global user.email "tadp.bot@gmail.com"
      - run: git config --global user.name "GreypineCI"
      - checkout
      - run:
          name: APT Installs
          command: |
            sudo apt-get update
            sudo apt-get install build-essential patch
            sudo apt-get install ruby-dev zlib1g-dev liblzma-dev libgmp-dev cmake
      - run:
          name: Install dependencies
          command: bundle install --jobs=10 --retry=3
      - run:
          name: Run the tests for backend
          command: bundle exec rake test
      - run:
          name: Publishing
          command: bundle exec rake publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: source